term xterm-256color

clipboard_control write-clipboard write-primary read-clipboard read-primary

window_padding_width 0

sync_to_monitor yes

background_opacity 0.75

background_blur 0

font_size 8.0

include current-theme.conf
