[app]
overall = { bg = "#1e2326" }

[mgr]
cwd = { fg = "#a7c080" }

find_keyword  = { fg = "#d3c6aa", italic = true }
find_position = { fg = "#a7c080", bg = "reset", italic = true }

marker_copied   = { fg = "#a7c080", bg = "#a7c080" }
marker_cut      = { fg = "#e67e80", bg = "#e67e80" }
marker_marked   = { fg = "#a7c080", bg = "#a7c080" }
marker_selected = { fg = "#a7c080", bg = "#a7c080" }

count_copied   = { fg = "#1e2326", bg = "#a7c080" }
count_cut      = { fg = "#1e2326", bg = "#e67e80" }
count_selected = { fg = "#1e2326", bg = "#a7c080" }

border_symbol = "│"
border_style  = { fg = "#323c41" }

[tabs]
active   = { fg = "#1e2326", bg = "#a7c080", bold = true }
inactive = { fg = "#d3c6aa", bg = "#323c41" }

[mode]
normal_main = { fg = "#1e2326", bg = "#a7c080", bold = true }
normal_alt  = { fg = "#d3c6aa", bg = "#323c41" }

select_main = { fg = "#1e2326", bg = "#a7c080", bold = true }
select_alt  = { fg = "#a7c080", bg = "#323c41" }

unset_main  = { fg = "#1e2326", bg = "#e67e80", bold = true }
unset_alt   = { fg = "#e67e80", bg = "#323c41" }

[indicator]
parent = { fg = "#1e2326", bg = "#d3c6aa" }
current = { fg = "#1e2326", bg = "#a7c080" }
preview = { fg = "#1e2326", bg = "#d3c6aa" }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label  = { fg = "#d3c6aa", bold = true }
progress_normal = { fg = "#a7c080", bg = "#323c41" }
progress_error  = { fg = "#d3c6aa", bg = "#e67e80" }

perm_type  = { fg = "#a7c080" }
perm_read  = { fg = "#d3c6aa" }
perm_write = { fg = "#e67e80" }
perm_exec  = { fg = "#a7c080" }
perm_sep   = { fg = "#323c41" }

[input]
border   = { fg = "#a7c080" }
title    = { fg = "#d3c6aa" }
value    = { fg = "#d3c6aa" }
selected = { reversed = true }

[pick]
border   = { fg = "#a7c080" }
active   = { fg = "#a7c080" }
inactive = { fg = "#d3c6aa" }

[confirm]
border     = { fg = "#a7c080" }
title      = { fg = "#a7c080" }
body       = { fg = "#d3c6aa" }
list       = { fg = "#d3c6aa" }
btn_yes    = { reversed = true }
btn_no     = { fg = "#d3c6aa" }

[cmp]
border = { fg = "#a7c080" }

[tasks]
border  = { fg = "#a7c080" }
title   = { fg = "#d3c6aa" }
hovered = { fg = "#a7c080", bold = true }

[which]
mask            = { bg = "#323c41" }
cand            = { fg = "#a7c080" }
rest            = { fg = "#d3c6aa" }
desc            = { fg = "#d3c6aa" }
separator       = "  "
separator_style = { fg = "#323c41" }

[help]
on      = { fg = "#a7c080" }
run     = { fg = "#a7c080" }
desc    = { fg = "#d3c6aa" }
hovered = { bg = "#323c41", bold = true }
footer  = { fg = "#d3c6aa", bg = "#323c41" }

[notify]
title_info  = { fg = "#a7c080" }
title_warn  = { fg = "#d3c6aa" }
title_error = { fg = "#e67e80" }

[filetype]
rules = [
	# Media
	{ mime = "image/*", fg = "#d3c6aa" },
	{ mime = "{audio,video}/*", fg = "#d3c6aa" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#e67e80" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#d3c6aa" },

	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#323c41" },

	# Special file
	{ url = "*", is = "orphan", bg = "#e67e80" },
	{ url = "*", is = "exec"  , fg = "#a7c080" },

	# Dummy file
	{ url = "*", is = "dummy", bg = "#e67e80" },
	{ url = "*/", is = "dummy", bg = "#e67e80" },

	# Fallback
	{ url = "*/", fg = "#a7c080" },
]

[spot]
border = { fg = "#a7c080" }
title  = { fg = "#a7c080" }
tbl_cell = { fg = "#a7c080", reversed = true }
tbl_col = { bold = true }

[icon]
dirs = [
	{ name = ".config", text = "", fg = "#a7c080" },
	{ name = ".git", text = "", fg = "#a7c080" },
	{ name = ".github", text = "", fg = "#a7c080" },
	{ name = ".npm", text = "", fg = "#a7c080" },
	{ name = "Desktop", text = "", fg = "#a7c080" },
	{ name = "Development", text = "", fg = "#a7c080" },
	{ name = "Documents", text = "", fg = "#a7c080" },
	{ name = "Downloads", text = "", fg = "#a7c080" },
	{ name = "Library", text = "", fg = "#a7c080" },
	{ name = "Movies", text = "", fg = "#a7c080" },
	{ name = "Music", text = "", fg = "#a7c080" },
	{ name = "Pictures", text = "", fg = "#a7c080" },
	{ name = "Public", text = "", fg = "#a7c080" },
	{ name = "Videos", text = "", fg = "#a7c080" },
]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#e67e80" },
	{ if = "link", text = "", fg = "#d3c6aa" },
	{ if = "block", text = "", fg = "#d3c6aa" },
	{ if = "char", text = "", fg = "#d3c6aa" },
	{ if = "fifo", text = "", fg = "#d3c6aa" },
	{ if = "sock", text = "", fg = "#d3c6aa" },
	{ if = "sticky", text = "", fg = "#d3c6aa" },
	{ if = "dummy", text = "", fg = "#e67e80" },

	# Fallback
	{ if = "dir", text = "", fg = "#a7c080" },
	{ if = "exec", text = "", fg = "#a7c080" },
	{ if = "!dir", text = "", fg = "#d3c6aa" },
]
